name: Cello CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build images
        run: |
          make docker-compose
      - name: Start services
        run: |
          MODE=dev make start
          sleep 10
      - name: Wait for API service to be ready
        run: |
          # Wait for API service to be fully ready
          timeout 120 bash -c 'until curl -f http://127.0.0.1:8080/api/v1/health || curl -f http://localhost:8080/api/v1/health; do sleep 5; done' || echo "API service health check failed, but continuing..."
          sleep 10
      - name: Run dashboard integration tests
        run: |
          make check-dashboard
      - name: Run API integration tests
        run: |
          make check-api
      - name: Stop services
        if: always()
        run: |
          MODE=dev make stop
      - name: Clean up containers and images
        if: always()
        run: |
          make clean
          docker system prune -f
